[green_agent]
agentbeats_id = "019ab9d3-797b-7490-b5e1-d7ed6226e311"
image = "ghcr.io/andrew7234/web3-green-agent:latest"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "guardian"
image = ""
env = {}

[[participants]]
agentbeats_id = ""
name = "penetrator"
image = ""
env = {}

[config]
# Add your assessment config here
